---
version: '3.3'

services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/walkie
      - NODE_ENV=production
      - APP_HOST=http://localhost:8000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0
    ports:
      - 27017:27017
    volumes:
      - "mongo_config:/data/configdb"
      - "mongo_data:/data/db"

volumes:
  mongo_config:
  mongo_data:
